#
# Module manifest for module 'NewManifest'
#
# Generated by: adm_mlp
#
# Generated on: 7/5/2016
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'Surly.PowerShell.Tools'

# Version number of this module.
ModuleVersion = '1.0'

# ID used to uniquely identify this module
GUID = '564d64ee-bef3-4b65-83b2-d66784fe176c'

# Author of this module
Author = 'adm_mlp'

# Company or vendor of this module
CompanyName = 'Unknown'

# Copyright statement for this module
Copyright = '(c) 2016 adm_mlp. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Surly.PowerShell.Tools'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '3.0'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
ProcessorArchitecture = 'None'

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module
FunctionsToExport = 'Show-HDSize', 'Compare-ADGroupMember', 'Get-AdapterInfo', 
               'Get-ComputerInfo', 'Get-DiskInfo', 'Get-OUFullyQualifiedDomainName', 
               'Get-ServiceInfo', 'Get-Uptime', 'Get-VMScreenShot', 'Get-WhatIsMyIP', 
               'Get-WQLQuery', 'New-RandomPassword', 'Restart-ComputerAndWait', 
               'Test-ADAuthentication', 'Write-Log'

# Cmdlets to export from this module
CmdletsToExport = 
               'Get-ADRootDSE New-ADObject Rename-ADObject Move-ADObject Get-ADObject Set-ADObject Remove-ADObject Restore-ADObject Add-ADGroupMember Add-ADPrincipalGroupMembership Get-ADGroup Get-ADGroupMember Get-ADPrincipalGroupMembership Get-ADAccountAuthorizationGroup New-ADGroup Remove-ADGroup Remove-ADGroupMember Remove-ADPrincipalGroupMembership Set-ADGroup Set-ADAccountControl Disable-ADAccount Enable-ADAccount Unlock-ADAccount Clear-ADAccountExpiration Set-ADAccountExpiration Set-ADAccountPassword Search-ADAccount Get-ADUser New-ADUser Remove-ADUser Set-ADUser Get-ADUserResultantPasswordPolicy New-ADComputer Get-ADComputer Set-ADComputer Remove-ADComputer Get-ADComputerServiceAccount Remove-ADComputerServiceAccount Add-ADComputerServiceAccount New-ADServiceAccount Get-ADServiceAccount Set-ADServiceAccount Remove-ADServiceAccount Install-ADServiceAccount Uninstall-ADServiceAccount Reset-ADServiceAccountPassword New-ADOrganizationalUnit Get-ADOrganizationalUnit Set-ADOrganizationalUnit Remove-ADOrganizationalUnit Move-ADDirectoryServer Move-ADDirectoryServerOperationMasterRole Get-ADAccountResultantPasswordReplicationPolicy Add-ADDomainControllerPasswordReplicationPolicy Get-ADDomainControllerPasswordReplicationPolicy Get-ADDomainControllerPasswordReplicationPolicyUsage Get-ADDomainController Remove-ADDomainControllerPasswordReplicationPolicy New-ADFineGrainedPasswordPolicy Get-ADFineGrainedPasswordPolicy Set-ADFineGrainedPasswordPolicy Remove-ADFineGrainedPasswordPolicy Get-ADFineGrainedPasswordPolicySubject Add-ADFineGrainedPasswordPolicySubject Remove-ADFineGrainedPasswordPolicySubject Get-ADDomain Set-ADDomain Set-ADDomainMode Get-ADForest Set-ADForest Set-ADForestMode Get-ADDefaultDomainPasswordPolicy Set-ADDefaultDomainPasswordPolicy Get-ADOptionalFeature Enable-ADOptionalFeature Disable-ADOptionalFeature'

# Variables to export from this module
VariablesToExport = @()

# Aliases to export from this module
AliasesToExport = @()

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        # Tags = @()

        # A URL to the license for this module.
        # LicenseUri = ''

        # A URL to the main website for this project.
        # ProjectUri = ''

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        # ReleaseNotes = ''

        # External dependent modules of this module
        # ExternalModuleDependencies = ''

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

